# docker-compose.yml
version: '3'
services:
  db:
    image: postgres:15.5 # postgres --versionで確認済み
    environment:
      POSTGRES_DB: app_development
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: ${POSTGRES_DB}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: ${POSTGRES_DB:-app_development}
      # POSTGRES_USER: ${POSTGRES_USER:-user}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: my_app_web
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
    environment:
      - RAILS_ENV=development
      # - RAILS_ENV=${RAILS_ENV}
      # - RAILS_ENV=production
      # - RENDER_DB_URL=${RENDER_DB_URL}
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
  bundle_data:
